# [Task]: T103
# [Spec]: F-009 (US11)
# [Description]: Kubernetes ServiceAccount for notification-service
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "notification-service.serviceAccountName" . }}
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
